# .devcontainer/Dockerfile
FROM jupiter-base:latest

USER root

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     gtkwave

# RUN pip install pyserial

# Use the same user as base
USER devuser
WORKDIR /home/devuser/workspace